export type SeriesItem = {
  code: string;
  ext: "jpg" | "png";
  image?: string;
  name: string;
};

export const series: SeriesItem[] = [
  { code: "MST", name: "無職轉生", ext: "jpg" },
  { code: "GIM", name: "學園偶像大師", ext: "jpg" },
  { code: "CSM", name: "鏈鋸人", ext: "jpg" },
  { code: "KJN", name: "我想成為影之強者！", ext: "jpg" },
  { code: "MCR", name: "超時空要塞", ext: "jpg" },
  { code: "MSS", name: "魔都精兵", ext: "jpg" },
  { code: "EVA", name: "新世紀福音戰士", ext: "jpg" },
  { code: "KGR", name: "神樂钵", ext: "jpg" },
  { code: "IYS", name: "犬夜叉", ext: "jpg" },
  { code: "NIK", name: "勝利女神 妮姬", ext: "jpg" },
  { code: "SLG", name: "我獨自升級", ext: "jpg" },
  { code: "KGD", name: "王者天下", ext: "jpg" },
  { code: "TKG", name: "東京喰種", ext: "jpg" },
  { code: "TLR", name: "出包王女", ext: "jpg" },
  { code: "SMD", name: "坂本日常", ext: "jpg" },
  { code: "FMA", name: "鋼之煉金術師", ext: "jpg" },
  { code: "REZ", name: "Re:從零開始的異世界生活", ext: "jpg" },
  { code: "MGS", name: "物語系列", ext: "jpg" },
  { code: "KIN", name: "筋肉人", ext: "jpg" },
  { code: "RNK", name: "浪客劍心", ext: "jpg" },
  { code: "WBK", name: "防風少年", ext: "jpg" },
  { code: "OPM", name: "一拳超人", ext: "jpg" },
  { code: "NGR", name: "2.5次元的誘惑", ext: "jpg" },
  { code: "CGD", name: "Code Geass 奪回的Rozé", ext: "jpg" },
  { code: "MMM", name: "魔法少女小圓", ext: "jpg" },
  { code: "ARK", name: "明日方舟", ext: "jpg" },
  { code: "KMR", name: "假面騎士", ext: "jpg" },
  { code: "SNF", name: "香格里拉 開拓異境", ext: "jpg" },
  { code: "SHY", name: "SHY靦腆英雄", ext: "jpg" },
  { code: "BCV", name: "黑色五葉草", ext: "jpg" },
  { code: "YYH", name: "幽遊白書", ext: "jpg" },
  { code: "KJ8", name: "怪獸8號", ext: "jpg" },
  { code: "GMR", name: "大怪獸卡美拉", ext: "jpg" },
  { code: "AOT", name: "進擊的巨人", ext: "jpg" },
  { code: "AND", name: "不死不運", ext: "jpg" },
  { code: "RLY", name: "超超超超超喜歡你的100女友", ext: "jpg" },
  { code: "HIQ", name: "排球少年", ext: "jpg" },
  { code: "SYN", name: "奇異賢伴 黑色天使", ext: "jpg" },
  { code: "SAO", name: "刀劍神域", ext: "jpg" },
  { code: "TRK", name: "美食獵人", ext: "jpg" },
  { code: "DST", name: "新石紀", ext: "jpg" },
  { code: "TOA", name: "破曉傳奇", ext: "jpg" },
  { code: "KMY", name: "鬼滅之刃", ext: "png" },
  { code: "IMS", name: "偶像大師 閃耀色彩", ext: "png" },
  { code: "BLK", name: "藍色監獄", ext: "jpg" },
  { code: "TKN", name: "鐵拳7", ext: "jpg" },
  { code: "TSK", name: "關於我轉生成史萊姆這檔事", ext: "jpg" },
  { code: "BTR", name: "我與機器子", ext: "jpg" },
  { code: "BLC", name: "死神 千年血戰篇", ext: "jpg" },
  { code: "MHA", name: "我的英雄學院", ext: "jpg" },
  { code: "GNT", name: "銀魂", ext: "jpg" },
  { code: "CGH", name: "Code Geass (魯路修)", ext: "png" },
  { code: "HTR", name: "獵人", ext: "png" },
  { code: "JJK", name: "咒術迴戰", ext: "png" },
  { code: "IMC", name: "偶像大師 灰姑娘女孩", ext: "png", image: "/cards/promo-imc/UAPR_IMC-1-027.png" },
  { code: "UNI", name: "UNION ARENA 通用卡", ext: "png", image: "/assets/union-arena.png" },
];
